repos:
- repo: https://github.com/pycqa/isort
  rev: 5.8.0
  hooks:
    - id: isort
      args: ["--multi-line=5", "--line-length=79", "--use-parentheses", "--filter-files"]
      exclude: "venv"
- repo: https://github.com/pycqa/flake8
  rev: 3bcadce2a9d91f4bb6afa97b5d2d1a82d7a1e937
  hooks:
    - id: flake8
      args: ["--select=B,C,E,F,W,T4,B9,Q0", "--ignore=W503", "--max-line-length=79", "--inline-quotes=single"]
      exclude: "(codingtest|init.py)"
      additional_dependencies: ["flake8-quotes"]
