exclude: ^(__pycache__|venv/|virtualenv/|\..+|alembic/)
stages: [commit]

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: 2.20.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
     - id: bandit
       args: ["-r ./", "-t B102,B105,B301,B608"]
       exclude: tests/*

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-executables-have-shebangs
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/PyCQA/isort
    rev: 5.9.2
    hooks:
      - id: isort
        args: ["--multi-line=5", "--line-length=79", "--use-parentheses", "--filter-files"]
#        args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ["--select=B,C,E,F,W,T4,B9,Q0", "--ignore=W503", "--max-line-length=79", "--inline-quotes=single"]
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
#         - flake8-quotes
#         - flake8-implicit-str-concat

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        additional_dependencies: [tokenize-rt==3.2.0]
