version: 1
disable_existing_loggers: false

formatters:
    brief:
        format: "%(asctime)s - %(levelname)-8s - %(name)s - %(message)s"
    precise:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: CRITICAL
        formatter: precise
        stream: ext://sys.stdout

    file:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: brief
        filename: logging.log
        maxBytes: 10485760 # 10MB
        backupCount: 10
        encoding: utf8

loggers:
    basic:
        level: INFO
        handlers: [file]
        propogate: no

root:
    level: NOTSET
    handlers: [console]
    propogate: yes
