"""first migration

Revision ID: 00253b96730c
Revises: 
Create Date: 2021-06-28 10:12:32.008439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00253b96730c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connectivity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username1', sa.String(length=50), nullable=False),
    sa.Column('username2', sa.String(length=50), nullable=False),
    sa.Column('invocation', sa.JSON(), server_default='{}', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_connectivity_username1_username2', 'connectivity', ['username1', 'username2'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_connectivity_username1_username2', table_name='connectivity')
    op.drop_table('connectivity')
    # ### end Alembic commands ###
