"""First migration

Revision ID: 68c41459fb49
Revises: 
Create Date: 2021-06-12 01:44:27.528122

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '68c41459fb49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connectivity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_handle1', sa.String(length=100), nullable=True),
    sa.Column('user_handle2', sa.String(length=100), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=True),
    sa.Column('organisations', sa.JSON(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_handle1', 'user_handle2', name='_user_handle_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connectivity')
    # ### end Alembic commands ###
